In [21]:
import numpy


def softmax1d(input):
    input = input.tolist()
    total = sum(input)
    if not total:
        # zero array
        return input

    result = []
    for val in input:
        result.append(float(val) / float(total))

    return numpy.array(result)


def softmax2d(input):
    intermed = numpy.transpose(input)
    result = []
    for val in intermed:
        row = softmax1d(val)
        result.append(row)

    result = numpy.transpose(result)
    return result


def softmax(input):
    if not len(input):
        return input

    if not isinstance(input[0], (int, long, float, complex)):
        return softmax2d(input)

    return softmax1d(input)

In [22]:
scores = numpy.array([1.0, 2.0, 3.0])

In [23]:
print softmax(scores)

[ 0.16666667  0.33333333  0.5       ]


In [26]:
scores = numpy.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

In [27]:
print softmax(scores)

[[ 0.16666667  0.14285714  0.2         0.33333333]
 [ 0.33333333  0.28571429  0.33333333  0.33333333]
 [ 0.5         0.57142857  0.46666667  0.33333333]]


In [29]:
0.09003057+0.24472847+0.66524096

1.0